spring:
  application:
    name: soundtouch-radio

soundtouch:
  host: 10.0.0.148
  http-port: 8090
  ws-port: 8080
  connect-timeout: 2s
  read-timeout: 5s

server:
  port: 8080

radio:
  stations:
    - id: vltava
      name: ČRo Vltava
      stream: http://icecast2.rozhlas.cz/vltava-mp3-128
      button: 1
    - id: radiowave
      name: ČRo Radio Wave
      stream: http://icecast2.rozhlas.cz/radiowave-mp3-128
      button: 2
